# frozen_string_literal: true

source 'https://rubygems.org'

gem 'coveralls', require: false
gem 'json'

group :test do
  gem 'capybara'
  gem 'capybara/rspec'
  gem 'rspec'
  gem 'rspec-core'
  gem 'rubocop'
  gem 'rubocop-performance'
  gem 'simplecov', require: false
  gem 'simplecov-console', require: false
end
